### ISSUE TITLE
Error compressing CEF build in VAR_CEF_BUILD_ONLY mode

### ISSUE THREAD

**Issue by alfred-epic** [mitchcapper/CefSharpDockerfiles#10]
When running the build in CEF only mode using process isolation mode locally I get an error:
  **Unable to find image 'powershell:latest' locally**
when running this step in build.ps1
`	RunProc -proc "docker" -redirect_output:$redirect_output -opts "run --name cef powershell Compress-Archive -Path C:/code/binaries/*.zip -CompressionLevel Fastest -DestinationPath /packages_cef"
`
I'm a docker for windows newbie but I think there is a missing "cef" here in the run command, so it can reference the cef container that was just created. It should be 
`	RunProc -proc "docker" -redirect_output:$redirect_output -opts "run --name cef cef powershell Compress-Archive -Path C:/code/binaries/*.zip -CompressionLevel Fastest -DestinationPath /packages_cef"
`
I'll attach a PR to this bug shortly with the suggested change.

**Comment by alfred-epic** [comment]
Pull request with the fix is here https://github.com/mitchcapper/CefSharpDockerfiles/pull/11

**Comment by mitchcapper** [comment]
Thanks for fixing!
