### ISSUE TITLE
Error while building latest versions

### ISSUE THREAD

**Issue by eugorer** [mitchcapper/CefSharpDockerfiles#3]
I've succesfully built version 63 of CefSharp 6 months ago, but I can't get it to work with any recent versions (tried 67, 69 and now 71). I've seen all kinds of errors on different VMs (Windows server 1709, 1803, 1809 and Windows 10 with HyperV) on AWS as well as Azure.

This is the most common error after ~2 hours in both win10 and server 2016: https://pastebin.com/Vbk5fC2k
versions.ps1: https://pastebin.com/CCh9AP5p (I've seen it called versions.ps1, version.ps1 and version_src.ps1, so they all exist and are the same)
docker config of my latest win10 build: https://pastebin.com/qZ5UQQvv

Windows Defender and UAC are disabled. I don't think there were any errors until after applying patches to cef(?).

**Comment by mitchcapper** [comment]
Were you able to resolve this? or was it just a setting issue?

**Comment by mitchcapper** [comment]
I think this is likely around the 17134 sdk from your logs. Will post further after some more tests.
